package bean;
// Generated 20/09/2023 16:54:33 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JlCliente generated by hbm2java
 */
@Entity
@Table(name="jl_cliente"
    ,catalog="db_joao_rocha"
)
public class JlCliente  implements java.io.Serializable {


     private int jlIdCliente;
     private String jlNome;
     private String jlApelido;
     private String jlCpf;
     private Date jlDataNasc;
     private String jlTelefone;
     private String jlEmail;
     private String jlRua;
     private String jlBairro;
     private String jlCep;
     private String jlNumero;
     private String jlComplemento;
     private String jlSexo;
     private String jlAlergia;
     private String jlEstadoCivil;

    public JlCliente() {
    }

	
    public JlCliente(int jlIdCliente) {
        this.jlIdCliente = jlIdCliente;
    }
    public JlCliente(int jlIdCliente, String jlNome, String jlApelido, String jlCpf, Date jlDataNasc, String jlTelefone, String jlEmail, String jlRua, String jlBairro, String jlCep, String jlNumero, String jlComplemento, String jlSexo, String jlAlergia, String jlEstadoCivil) {
       this.jlIdCliente = jlIdCliente;
       this.jlNome = jlNome;
       this.jlApelido = jlApelido;
       this.jlCpf = jlCpf;
       this.jlDataNasc = jlDataNasc;
       this.jlTelefone = jlTelefone;
       this.jlEmail = jlEmail;
       this.jlRua = jlRua;
       this.jlBairro = jlBairro;
       this.jlCep = jlCep;
       this.jlNumero = jlNumero;
       this.jlComplemento = jlComplemento;
       this.jlSexo = jlSexo;
       this.jlAlergia = jlAlergia;
       this.jlEstadoCivil = jlEstadoCivil;
    }
   
     @Id 

    
    @Column(name="jl_id_cliente", unique=true, nullable=false)
    public int getJlIdCliente() {
        return this.jlIdCliente;
    }
    
    public void setJlIdCliente(int jlIdCliente) {
        this.jlIdCliente = jlIdCliente;
    }

    
    @Column(name="jl_nome", length=50)
    public String getJlNome() {
        return this.jlNome;
    }
    
    public void setJlNome(String jlNome) {
        this.jlNome = jlNome;
    }

    
    @Column(name="jl_apelido", length=50)
    public String getJlApelido() {
        return this.jlApelido;
    }
    
    public void setJlApelido(String jlApelido) {
        this.jlApelido = jlApelido;
    }

    
    @Column(name="jl_cpf", length=14)
    public String getJlCpf() {
        return this.jlCpf;
    }
    
    public void setJlCpf(String jlCpf) {
        this.jlCpf = jlCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jl_dataNasc", length=10)
    public Date getJlDataNasc() {
        return this.jlDataNasc;
    }
    
    public void setJlDataNasc(Date jlDataNasc) {
        this.jlDataNasc = jlDataNasc;
    }

    
    @Column(name="jl_telefone", length=11)
    public String getJlTelefone() {
        return this.jlTelefone;
    }
    
    public void setJlTelefone(String jlTelefone) {
        this.jlTelefone = jlTelefone;
    }

    
    @Column(name="jl_email", length=80)
    public String getJlEmail() {
        return this.jlEmail;
    }
    
    public void setJlEmail(String jlEmail) {
        this.jlEmail = jlEmail;
    }

    
    @Column(name="jl_rua", length=70)
    public String getJlRua() {
        return this.jlRua;
    }
    
    public void setJlRua(String jlRua) {
        this.jlRua = jlRua;
    }

    
    @Column(name="jl_bairro", length=45)
    public String getJlBairro() {
        return this.jlBairro;
    }
    
    public void setJlBairro(String jlBairro) {
        this.jlBairro = jlBairro;
    }

    
    @Column(name="jl_cep", length=10)
    public String getJlCep() {
        return this.jlCep;
    }
    
    public void setJlCep(String jlCep) {
        this.jlCep = jlCep;
    }

    
    @Column(name="jl_numero", length=4)
    public String getJlNumero() {
        return this.jlNumero;
    }
    
    public void setJlNumero(String jlNumero) {
        this.jlNumero = jlNumero;
    }

    
    @Column(name="jl_complemento", length=100)
    public String getJlComplemento() {
        return this.jlComplemento;
    }
    
    public void setJlComplemento(String jlComplemento) {
        this.jlComplemento = jlComplemento;
    }

    
    @Column(name="jl_sexo", length=1)
    public String getJlSexo() {
        return this.jlSexo;
    }
    
    public void setJlSexo(String jlSexo) {
        this.jlSexo = jlSexo;
    }

    
    @Column(name="jl_alergia", length=50)
    public String getJlAlergia() {
        return this.jlAlergia;
    }
    
    public void setJlAlergia(String jlAlergia) {
        this.jlAlergia = jlAlergia;
    }

    
    @Column(name="jl_estado_civil", length=20)
    public String getJlEstadoCivil() {
        return this.jlEstadoCivil;
    }
    
    public void setJlEstadoCivil(String jlEstadoCivil) {
        this.jlEstadoCivil = jlEstadoCivil;
    }




}


