package bean;
// Generated 20/09/2023 16:54:33 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JlUsuario generated by hbm2java
 */
@Entity
@Table(name="jl_usuario"
    ,catalog="db_joao_rocha"
)
public class JlUsuario  implements java.io.Serializable {


     private int jlIdUsuario;
     private String jlNome;
     private String jlApelido;
     private String jlCpf;
     private Date jlDataNascimento;
     private String jlSenha;
     private Integer jlNivel;
     private String jlAtivo;

    public JlUsuario() {
    }

	
    public JlUsuario(int jlIdUsuario) {
        this.jlIdUsuario = jlIdUsuario;
    }
    public JlUsuario(int jlIdUsuario, String jlNome, String jlApelido, String jlCpf, Date jlDataNascimento, String jlSenha, Integer jlNivel, String jlAtivo) {
       this.jlIdUsuario = jlIdUsuario;
       this.jlNome = jlNome;
       this.jlApelido = jlApelido;
       this.jlCpf = jlCpf;
       this.jlDataNascimento = jlDataNascimento;
       this.jlSenha = jlSenha;
       this.jlNivel = jlNivel;
       this.jlAtivo = jlAtivo;
    }
   
     @Id 

    
    @Column(name="jl_id_usuario", unique=true, nullable=false)
    public int getJlIdUsuario() {
        return this.jlIdUsuario;
    }
    
    public void setJlIdUsuario(int jlIdUsuario) {
        this.jlIdUsuario = jlIdUsuario;
    }

    
    @Column(name="jl_nome", length=50)
    public String getJlNome() {
        return this.jlNome;
    }
    
    public void setJlNome(String jlNome) {
        this.jlNome = jlNome;
    }

    
    @Column(name="jl_apelido", length=50)
    public String getJlApelido() {
        return this.jlApelido;
    }
    
    public void setJlApelido(String jlApelido) {
        this.jlApelido = jlApelido;
    }

    
    @Column(name="jl_cpf", length=14)
    public String getJlCpf() {
        return this.jlCpf;
    }
    
    public void setJlCpf(String jlCpf) {
        this.jlCpf = jlCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jl_dataNascimento", length=10)
    public Date getJlDataNascimento() {
        return this.jlDataNascimento;
    }
    
    public void setJlDataNascimento(Date jlDataNascimento) {
        this.jlDataNascimento = jlDataNascimento;
    }

    
    @Column(name="jl_senha", length=20)
    public String getJlSenha() {
        return this.jlSenha;
    }
    
    public void setJlSenha(String jlSenha) {
        this.jlSenha = jlSenha;
    }

    
    @Column(name="jl_nivel")
    public Integer getJlNivel() {
        return this.jlNivel;
    }
    
    public void setJlNivel(Integer jlNivel) {
        this.jlNivel = jlNivel;
    }

    
    @Column(name="jl_ativo", length=1)
    public String getJlAtivo() {
        return this.jlAtivo;
    }
    
    public void setJlAtivo(String jlAtivo) {
        this.jlAtivo = jlAtivo;
    }




}


