package bean;
// Generated 20/09/2023 16:54:33 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JlVendedor generated by hbm2java
 */
@Entity
@Table(name="jl_vendedor"
    ,catalog="db_joao_rocha"
)
public class JlVendedor  implements java.io.Serializable {


     private int jlIdVendedor;
     private String jlNome;
     private String jlCpf;
     private Date jlDataNasc;
     private String jlEmail;
     private Set jlVendases = new HashSet(0);
     private Set jlProdutos = new HashSet(0);

    public JlVendedor() {
    }

	
    public JlVendedor(int jlIdVendedor) {
        this.jlIdVendedor = jlIdVendedor;
    }
    public JlVendedor(int jlIdVendedor, String jlNome, String jlCpf, Date jlDataNasc, String jlEmail, Set jlVendases, Set jlProdutos) {
       this.jlIdVendedor = jlIdVendedor;
       this.jlNome = jlNome;
       this.jlCpf = jlCpf;
       this.jlDataNasc = jlDataNasc;
       this.jlEmail = jlEmail;
       this.jlVendases = jlVendases;
       this.jlProdutos = jlProdutos;
    }
   
     @Id 

    
    @Column(name="jl_id_vendedor", unique=true, nullable=false)
    public int getJlIdVendedor() {
        return this.jlIdVendedor;
    }
    
    public void setJlIdVendedor(int jlIdVendedor) {
        this.jlIdVendedor = jlIdVendedor;
    }

    
    @Column(name="jl_nome", length=50)
    public String getJlNome() {
        return this.jlNome;
    }
    
    public void setJlNome(String jlNome) {
        this.jlNome = jlNome;
    }

    
    @Column(name="jl_cpf", length=14)
    public String getJlCpf() {
        return this.jlCpf;
    }
    
    public void setJlCpf(String jlCpf) {
        this.jlCpf = jlCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jl_dataNasc", length=10)
    public Date getJlDataNasc() {
        return this.jlDataNasc;
    }
    
    public void setJlDataNasc(Date jlDataNasc) {
        this.jlDataNasc = jlDataNasc;
    }

    
    @Column(name="jl_email", length=50)
    public String getJlEmail() {
        return this.jlEmail;
    }
    
    public void setJlEmail(String jlEmail) {
        this.jlEmail = jlEmail;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="jlVendedor")
    public Set getJlVendases() {
        return this.jlVendases;
    }
    
    public void setJlVendases(Set jlVendases) {
        this.jlVendases = jlVendases;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="jlVendedor")
    public Set getJlProdutos() {
        return this.jlProdutos;
    }
    
    public void setJlProdutos(Set jlProdutos) {
        this.jlProdutos = jlProdutos;
    }




}


