package bean;
// Generated 20/09/2023 16:54:33 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JlVendas generated by hbm2java
 */
@Entity
@Table(name="jl_vendas"
    ,catalog="db_joao_rocha"
)
public class JlVendas  implements java.io.Serializable {


     private int jlIdvendas;
     private JlProduto jlProduto;
     private JlVendedor jlVendedor;
     private Date jlData;
     private BigDecimal jlTotal;

    public JlVendas() {
    }

	
    public JlVendas(int jlIdvendas, JlProduto jlProduto, JlVendedor jlVendedor) {
        this.jlIdvendas = jlIdvendas;
        this.jlProduto = jlProduto;
        this.jlVendedor = jlVendedor;
    }
    public JlVendas(int jlIdvendas, JlProduto jlProduto, JlVendedor jlVendedor, Date jlData, BigDecimal jlTotal) {
       this.jlIdvendas = jlIdvendas;
       this.jlProduto = jlProduto;
       this.jlVendedor = jlVendedor;
       this.jlData = jlData;
       this.jlTotal = jlTotal;
    }
   
     @Id 

    
    @Column(name="jl_idvendas", unique=true, nullable=false)
    public int getJlIdvendas() {
        return this.jlIdvendas;
    }
    
    public void setJlIdvendas(int jlIdvendas) {
        this.jlIdvendas = jlIdvendas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="produto_id_produto", nullable=false)
    public JlProduto getJlProduto() {
        return this.jlProduto;
    }
    
    public void setJlProduto(JlProduto jlProduto) {
        this.jlProduto = jlProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vendedor_id_vendedor", nullable=false)
    public JlVendedor getJlVendedor() {
        return this.jlVendedor;
    }
    
    public void setJlVendedor(JlVendedor jlVendedor) {
        this.jlVendedor = jlVendedor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jl_data", length=10)
    public Date getJlData() {
        return this.jlData;
    }
    
    public void setJlData(Date jlData) {
        this.jlData = jlData;
    }

    
    @Column(name="jl_total", precision=10)
    public BigDecimal getJlTotal() {
        return this.jlTotal;
    }
    
    public void setJlTotal(BigDecimal jlTotal) {
        this.jlTotal = jlTotal;
    }




}


